module.exports = [{
	"y": 10,
	"x": 14,
	"value": 59,
	"bullet": "http://site.je/app/img/nucleo-social-icons/svg/social-1_logo-facebook.svg",
	"title": "Facebook"
}, {
	"y": 5,
	"x": 3,
	"value": 50,
	"bullet": "http://site.je/app/img/nucleo-social-icons/svg/social-1_logo-twitter.svg",
	"title": "Twitter"
}, {
	"y": -10,
	"x": 8,
	"value": 19,
	"bullet": "http://site.je/app/img/nucleo-social-icons/svg/social-1_logo-pinterest.svg",
	"title": "Pinterest"
}, {
	"y": -6,
	"x": 5,
	"value": 65,
	"bullet": "http://site.je/app/img/nucleo-social-icons/svg/social-1_logo-google-plus.svg",
	"title": "Google+"
}, {
	"y": 15,
	"x": -4,
	"value": 92,
	"bullet": "http://site.je/app/img/nucleo-social-icons/svg/social-1_logo-whatsapp.svg",
	"title": "WhatsApp"
}, {
	"y": 13,
	"x": 1,
	"value": 8,
	"bullet": "http://site.je/app/img/nucleo-social-icons/svg/social-1_logo-instagram.svg",
	"title": "Instagram"
}, {
	"y": 1,
	"x": 6,
	"value": 35,
	"bullet": "http://site.je/app/img/nucleo-social-icons/svg/social-1_logo-linkedin.svg",
	"title": "LinkedIn"
}];